"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import Section from "./components/layout/Section";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <Header />
      <Section/>
      <main>{children}</main>
      <Footer />
    </>
  );
}
